import { IdeaCardData, DashboardStats, TrendData } from "./types";

export const mockIdeas: IdeaCardData[] = [
  {
    id: "1",
    title: "Semaglutide Dosing & Reconstitution Visual Guide",
    slug: "semaglutide-dosing-reconstitution-guide",
    summary: "Interactive visual guide covering semaglutide reconstitution, dosing titration schedules, and injection site rotation. Massive demand gap — 2,847 Reddit questions about reconstitution this month alone.",
    status: "detected",
    compositeScore: 92,
    trendScore: 95,
    demandScore: 98,
    competitionScore: 85,
    feasibilityScore: 80,
    revenuePotentialScore: 82,
    confidenceScore: 91,
    category: "template",
    subcategory: "dosing guide",
    peptideTopics: ["Semaglutide", "GLP-1"],
    productType: ["template", "calculator"],
    subNiche: ["weight_loss"],
    targetAudience: "Adults 25-55 starting semaglutide for weight management",
    opportunityType: "gap_opportunity",
    complianceFlag: "yellow",
    complianceNotes: "Dosage content may be interpreted as medical advice. Include disclaimers.",
    googleTrendsScore: 94,
    googleTrendsDirection: "rising",
    redditMentionCount: 4231,
    redditQuestionCount: 2847,
    youtubeVideoCount: 340,
    etsyCompetitorCount: 6,
    whopCompetitorCount: 2,
    estimatedPriceRange: "$12.99 - $24.99",
    effortToBuild: "low",
    timeToBuild: "3-5 days",
    sourceUrls: ["https://reddit.com/r/Semaglutide", "https://trends.google.com"],
    sourcePlatforms: ["reddit", "google_trends", "etsy"],
    discoveredAt: "2026-04-14T08:30:00Z",
    updatedAt: "2026-04-14T12:00:00Z",
  },
  {
    id: "2",
    title: "Interactive BPC-157 + TB-500 Stacking Protocol Builder",
    slug: "bpc157-tb500-stacking-protocol-builder",
    summary: "Web-based tool that generates personalized stacking protocols for BPC-157 and TB-500 based on injury type, body weight, and goals. The most asked-about stack on r/Peptides with zero existing digital tools.",
    status: "detected",
    compositeScore: 88,
    trendScore: 82,
    demandScore: 90,
    competitionScore: 95,
    feasibilityScore: 75,
    revenuePotentialScore: 88,
    confidenceScore: 85,
    category: "saas_tool",
    subcategory: "protocol builder",
    peptideTopics: ["BPC-157", "TB-500"],
    productType: ["saas_tool", "calculator"],
    subNiche: ["bodybuilding", "recovery"],
    targetAudience: "Intermediate biohackers and athletes dealing with injuries",
    opportunityType: "first_mover",
    complianceFlag: "yellow",
    complianceNotes: "Stacking protocols could be seen as prescribing. Frame as educational.",
    googleTrendsScore: 76,
    googleTrendsDirection: "rising",
    redditMentionCount: 1892,
    redditQuestionCount: 743,
    youtubeVideoCount: 156,
    etsyCompetitorCount: 0,
    whopCompetitorCount: 0,
    estimatedPriceRange: "$9.99/mo - $19.99/mo",
    effortToBuild: "medium",
    timeToBuild: "2-3 weeks",
    sourceUrls: ["https://reddit.com/r/Peptides"],
    sourcePlatforms: ["reddit", "google_trends"],
    discoveredAt: "2026-04-13T14:00:00Z",
    updatedAt: "2026-04-14T10:00:00Z",
  },
  {
    id: "3",
    title: "Retatrutide Protocol Builder & Tracker",
    slug: "retatrutide-protocol-builder-tracker",
    summary: "BREAKOUT OPPORTUNITY: Retatrutide searches up 890% in 30 days. Zero competitors. Web-based calculator/planner where users input stats and get customized retatrutide dosing protocol with tracking.",
    status: "detected",
    compositeScore: 91,
    trendScore: 99,
    demandScore: 85,
    competitionScore: 100,
    feasibilityScore: 72,
    revenuePotentialScore: 90,
    confidenceScore: 78,
    category: "saas_tool",
    subcategory: "protocol planner",
    peptideTopics: ["Retatrutide", "GLP-1"],
    productType: ["saas_tool", "tracker"],
    subNiche: ["weight_loss"],
    targetAudience: "Early adopters exploring next-gen GLP-1 triple agonists",
    opportunityType: "first_mover",
    complianceFlag: "yellow",
    complianceNotes: "New compound — regulatory landscape unclear. Strong disclaimers needed.",
    googleTrendsScore: 99,
    googleTrendsDirection: "breakout",
    redditMentionCount: 2340,
    redditQuestionCount: 890,
    youtubeVideoCount: 89,
    etsyCompetitorCount: 0,
    whopCompetitorCount: 0,
    estimatedPriceRange: "$9.99/mo",
    effortToBuild: "medium",
    timeToBuild: "2-3 weeks",
    sourceUrls: ["https://trends.google.com", "https://reddit.com/r/Peptides"],
    sourcePlatforms: ["google_trends", "reddit"],
    discoveredAt: "2026-04-14T06:00:00Z",
    updatedAt: "2026-04-14T11:00:00Z",
  },
  {
    id: "4",
    title: "GHK-Cu Skincare Protocol & Product Comparison Guide",
    slug: "ghk-cu-skincare-protocol-guide",
    summary: "Comprehensive guide covering GHK-Cu skincare applications, DIY formulation recipes, product comparisons, and before/after tracking templates. Crossover appeal between peptide and skincare audiences.",
    status: "reviewing",
    compositeScore: 76,
    trendScore: 72,
    demandScore: 78,
    competitionScore: 70,
    feasibilityScore: 85,
    revenuePotentialScore: 68,
    confidenceScore: 72,
    category: "ebook",
    subcategory: "skincare guide",
    peptideTopics: ["GHK-Cu"],
    productType: ["ebook", "template"],
    subNiche: ["skincare", "anti-aging"],
    targetAudience: "Women 30-55 interested in peptide-based skincare",
    opportunityType: "proven_model",
    complianceFlag: "green",
    complianceNotes: "Topical skincare is lower risk. Keep claims cosmetic, not medical.",
    googleTrendsScore: 65,
    googleTrendsDirection: "rising",
    redditMentionCount: 567,
    redditQuestionCount: 234,
    youtubeVideoCount: 78,
    etsyCompetitorCount: 12,
    whopCompetitorCount: 1,
    estimatedPriceRange: "$14.99 - $29.99",
    effortToBuild: "low",
    timeToBuild: "1-2 weeks",
    sourceUrls: ["https://reddit.com/r/SkincareAddiction"],
    sourcePlatforms: ["reddit", "etsy", "youtube"],
    discoveredAt: "2026-04-12T10:00:00Z",
    updatedAt: "2026-04-14T08:00:00Z",
  },
  {
    id: "5",
    title: "Peptide Reconstitution Calculator App",
    slug: "peptide-reconstitution-calculator",
    summary: "Simple but powerful web calculator: input vial size (mg), BAC water volume (mL), desired dose (mcg), and get exact syringe measurements with visual insulin syringe overlay. Most requested tool on peptide forums.",
    status: "approved",
    compositeScore: 85,
    trendScore: 70,
    demandScore: 95,
    competitionScore: 60,
    feasibilityScore: 95,
    revenuePotentialScore: 55,
    confidenceScore: 92,
    category: "calculator",
    subcategory: "reconstitution calculator",
    peptideTopics: ["General Peptides"],
    productType: ["calculator", "saas_tool"],
    subNiche: ["general"],
    targetAudience: "All peptide users, especially beginners",
    opportunityType: "improvement",
    complianceFlag: "green",
    complianceNotes: "Math tool — no medical claims. Safe.",
    googleTrendsScore: 58,
    googleTrendsDirection: "stable",
    redditMentionCount: 890,
    redditQuestionCount: 567,
    youtubeVideoCount: 45,
    etsyCompetitorCount: 8,
    whopCompetitorCount: 3,
    estimatedPriceRange: "$4.99 - $9.99",
    effortToBuild: "low",
    timeToBuild: "3-5 days",
    sourceUrls: ["https://reddit.com/r/Peptides"],
    sourcePlatforms: ["reddit", "google_trends"],
    discoveredAt: "2026-04-10T16:00:00Z",
    updatedAt: "2026-04-13T14:00:00Z",
  },
  {
    id: "6",
    title: "Tirzepatide Complete Weight Loss Course",
    slug: "tirzepatide-weight-loss-course",
    summary: "8-module video course covering tirzepatide mechanisms, dosing escalation, nutrition optimization during GLP-1 use, exercise modifications, and side effect management. Premium content format.",
    status: "incubating",
    compositeScore: 79,
    trendScore: 88,
    demandScore: 82,
    competitionScore: 55,
    feasibilityScore: 50,
    revenuePotentialScore: 92,
    confidenceScore: 80,
    category: "course",
    subcategory: "weight loss course",
    peptideTopics: ["Tirzepatide", "GLP-1"],
    productType: ["course"],
    subNiche: ["weight_loss"],
    targetAudience: "Adults 30-60 using or considering tirzepatide",
    opportunityType: "proven_model",
    complianceFlag: "red",
    complianceNotes: "Video course with health claims requires careful legal review. FDA regulations on weight loss claims apply.",
    googleTrendsScore: 87,
    googleTrendsDirection: "rising",
    redditMentionCount: 3200,
    redditQuestionCount: 1200,
    youtubeVideoCount: 450,
    etsyCompetitorCount: 15,
    whopCompetitorCount: 5,
    estimatedPriceRange: "$49.99 - $149.99",
    effortToBuild: "high",
    timeToBuild: "4-6 weeks",
    sourceUrls: ["https://reddit.com/r/Tirzepatide", "https://youtube.com"],
    sourcePlatforms: ["reddit", "youtube", "google_trends", "etsy"],
    discoveredAt: "2026-04-08T12:00:00Z",
    updatedAt: "2026-04-14T06:00:00Z",
  },
  {
    id: "7",
    title: "Peptide Cycle Planner & Blood Work Tracker",
    slug: "peptide-cycle-planner-blood-work",
    summary: "SaaS tool for planning multi-peptide cycles with calendar view, dosing reminders, blood work result logging, and trend visualization. Addresses the #1 pain point: tracking complex protocols.",
    status: "detected",
    compositeScore: 83,
    trendScore: 68,
    demandScore: 86,
    competitionScore: 90,
    feasibilityScore: 60,
    revenuePotentialScore: 88,
    confidenceScore: 75,
    category: "saas_tool",
    subcategory: "cycle planner",
    peptideTopics: ["General Peptides", "BPC-157", "Ipamorelin", "CJC-1295"],
    productType: ["saas_tool", "tracker"],
    subNiche: ["bodybuilding", "longevity"],
    targetAudience: "Experienced peptide users running complex multi-peptide protocols",
    opportunityType: "gap_opportunity",
    complianceFlag: "yellow",
    complianceNotes: "Tracking tool — relatively safe. Avoid framing as medical record system.",
    googleTrendsScore: 54,
    googleTrendsDirection: "stable",
    redditMentionCount: 670,
    redditQuestionCount: 340,
    youtubeVideoCount: 23,
    etsyCompetitorCount: 3,
    whopCompetitorCount: 1,
    estimatedPriceRange: "$14.99/mo",
    effortToBuild: "high",
    timeToBuild: "4-8 weeks",
    sourceUrls: ["https://reddit.com/r/Peptides", "https://reddit.com/r/Biohackers"],
    sourcePlatforms: ["reddit"],
    discoveredAt: "2026-04-11T20:00:00Z",
    updatedAt: "2026-04-14T09:00:00Z",
  },
  {
    id: "8",
    title: "Ipamorelin + CJC-1295 Sleep Optimization Guide",
    slug: "ipamorelin-cjc1295-sleep-guide",
    summary: "Niche ebook focusing on using Ipamorelin + CJC-1295 specifically for deep sleep optimization. Includes timing protocols, sleep tracking integration advice, and dietary synergies.",
    status: "declined",
    compositeScore: 52,
    trendScore: 45,
    demandScore: 58,
    competitionScore: 65,
    feasibilityScore: 90,
    revenuePotentialScore: 40,
    confidenceScore: 55,
    category: "ebook",
    subcategory: "sleep guide",
    peptideTopics: ["Ipamorelin", "CJC-1295"],
    productType: ["ebook"],
    subNiche: ["sleep"],
    targetAudience: "Biohackers interested in sleep optimization",
    opportunityType: "proven_model",
    complianceFlag: "yellow",
    complianceNotes: "Sleep health claims need careful framing.",
    googleTrendsScore: 35,
    googleTrendsDirection: "stable",
    redditMentionCount: 230,
    redditQuestionCount: 89,
    youtubeVideoCount: 34,
    etsyCompetitorCount: 4,
    whopCompetitorCount: 0,
    estimatedPriceRange: "$9.99 - $14.99",
    effortToBuild: "low",
    timeToBuild: "1 week",
    sourceUrls: ["https://reddit.com/r/Peptides"],
    sourcePlatforms: ["reddit"],
    discoveredAt: "2026-04-09T14:00:00Z",
    updatedAt: "2026-04-12T16:00:00Z",
  },
];

export const mockDashboardStats: DashboardStats = {
  totalIdeas: 47,
  pendingReview: 12,
  approved: 8,
  declined: 15,
  incubating: 4,
  avgScore: 71.3,
  ideasThisWeek: 9,
  topTrendingTopic: "Retatrutide",
};

export const mockTrends: TrendData[] = [
  { keyword: "retatrutide", platform: "google_trends", value: 99, direction: "breakout", changePercent: 890 },
  { keyword: "semaglutide dosing", platform: "google_trends", value: 94, direction: "rising", changePercent: 45 },
  { keyword: "BPC-157 TB-500 stack", platform: "reddit", value: 82, direction: "rising", changePercent: 32 },
  { keyword: "peptide reconstitution", platform: "google_trends", value: 71, direction: "rising", changePercent: 28 },
  { keyword: "tirzepatide guide", platform: "google_trends", value: 87, direction: "rising", changePercent: 55 },
  { keyword: "GHK-Cu skincare", platform: "reddit", value: 65, direction: "rising", changePercent: 18 },
  { keyword: "peptide cycle planner", platform: "google_trends", value: 54, direction: "stable", changePercent: 5 },
  { keyword: "ipamorelin sleep", platform: "google_trends", value: 35, direction: "stable", changePercent: -2 },
  { keyword: "peptide calculator", platform: "google_trends", value: 68, direction: "rising", changePercent: 22 },
  { keyword: "MK-677 guide", platform: "reddit", value: 58, direction: "declining", changePercent: -12 },
  { keyword: "epithalon longevity", platform: "google_trends", value: 42, direction: "rising", changePercent: 15 },
  { keyword: "PT-141", platform: "google_trends", value: 48, direction: "stable", changePercent: 3 },
];

export const mockCompetitors = [
  {
    id: "c1",
    name: "PeptideHub Guides",
    platform: "etsy",
    profileUrl: "https://etsy.com/shop/PeptideHubGuides",
    totalProducts: 12,
    estimatedRevenue: "$3,200/mo",
    watchPriority: "high" as const,
    isActive: true,
    createdAt: "2026-03-01T00:00:00Z",
    products: [
      { name: "BPC-157 Complete Guide", price: 12.99, reviews: 87, estimatedSales: 1200 },
      { name: "Peptide Dosing Chart Bundle", price: 9.99, reviews: 45, estimatedSales: 650 },
      { name: "Semaglutide Journal", price: 14.99, reviews: 120, estimatedSales: 1800 },
    ],
  },
  {
    id: "c2",
    name: "BiohackPro Academy",
    platform: "whop",
    profileUrl: "https://whop.com/biohackpro",
    totalProducts: 4,
    estimatedRevenue: "$8,500/mo",
    watchPriority: "high" as const,
    isActive: true,
    createdAt: "2026-02-15T00:00:00Z",
    products: [
      { name: "Peptide Mastery Course", price: 49.99, reviews: 230, estimatedSales: 400 },
      { name: "Monthly Protocol Updates", price: 19.99, reviews: 89, estimatedSales: 300 },
    ],
  },
  {
    id: "c3",
    name: "StackScience",
    platform: "gumroad",
    profileUrl: "https://stackscience.gumroad.com",
    totalProducts: 7,
    estimatedRevenue: "$1,800/mo",
    watchPriority: "normal" as const,
    isActive: true,
    createdAt: "2026-01-20T00:00:00Z",
    products: [
      { name: "Peptide Stacking Bible", price: 24.99, reviews: 34, estimatedSales: 280 },
      { name: "GLP-1 Quick Start", price: 7.99, reviews: 67, estimatedSales: 900 },
    ],
  },
];

export const mockGoldenRules = [
  {
    id: "r1",
    ruleType: "must_have" as const,
    ruleText: "Recurring revenue model preferred over one-time sales",
    direction: "boost" as const,
    weight: 1.5,
    importance: 1.0,
    isActive: true,
    approved: true,
    source: "manual" as const,
    appliedCount: 23,
    overrideCount: 2,
  },
  {
    id: "r2",
    ruleType: "must_have" as const,
    ruleText: "Product must be buildable in under 2 weeks with our team",
    direction: "require" as const,
    weight: 1.0,
    importance: 1.0,
    isActive: true,
    approved: true,
    source: "manual" as const,
    appliedCount: 47,
    overrideCount: 5,
  },
  {
    id: "r3",
    ruleType: "must_avoid" as const,
    ruleText: "No products that require showing my face",
    direction: "block" as const,
    weight: 1.0,
    importance: 1.0,
    isActive: true,
    approved: true,
    source: "manual" as const,
    appliedCount: 8,
    overrideCount: 0,
  },
  {
    id: "r4",
    ruleType: "must_avoid" as const,
    ruleText: "Avoid anything requiring medical credentials to sell legally",
    direction: "penalize" as const,
    weight: 1.5,
    importance: 1.0,
    isActive: true,
    approved: true,
    source: "manual" as const,
    appliedCount: 15,
    overrideCount: 1,
  },
  {
    id: "r5",
    ruleType: "prefer" as const,
    ruleText: "SaaS/tool products over info products",
    direction: "boost" as const,
    weight: 1.2,
    importance: 0.8,
    isActive: true,
    approved: true,
    source: "learned" as const,
    appliedCount: 30,
    overrideCount: 4,
  },
  {
    id: "r6",
    ruleType: "prefer" as const,
    ruleText: "Products that can be enhanced with AI over time",
    direction: "boost" as const,
    weight: 1.1,
    importance: 0.7,
    isActive: true,
    approved: true,
    source: "manual" as const,
    appliedCount: 12,
    overrideCount: 1,
  },
  {
    id: "r7",
    ruleType: "deprioritize" as const,
    ruleText: "Pure printables (too low ticket)",
    direction: "penalize" as const,
    weight: 0.8,
    importance: 0.6,
    isActive: true,
    approved: true,
    source: "learned" as const,
    appliedCount: 9,
    overrideCount: 3,
  },
  {
    id: "r8",
    ruleType: "must_avoid" as const,
    ruleText: "Avoid simple reference/glossary products. Focus on problem-solving products that address confusion, planning, or safety concerns.",
    direction: "block" as const,
    weight: 1.0,
    importance: 1.0,
    isActive: true,
    approved: true,
    source: "conversation" as const,
    appliedCount: 6,
    overrideCount: 0,
  },
];

export const mockActivity = [
  { id: "a1", action: "idea_detected", entityType: "idea", details: { title: "Retatrutide Protocol Builder", score: 91 }, createdAt: "2026-04-14T06:00:00Z" },
  { id: "a2", action: "scraper_completed", entityType: "source", details: { scraper: "Reddit", signals: 34, ideas: 3 }, createdAt: "2026-04-14T04:00:00Z" },
  { id: "a3", action: "idea_approved", entityType: "idea", details: { title: "Peptide Reconstitution Calculator" }, createdAt: "2026-04-13T14:00:00Z" },
  { id: "a4", action: "rule_created", entityType: "rule", details: { rule: "Avoid simple reference/glossary products" }, createdAt: "2026-04-13T12:00:00Z" },
  { id: "a5", action: "idea_declined", entityType: "idea", details: { title: "Generic Peptide Glossary PDF", reason: "Glossaries are garbage" }, createdAt: "2026-04-13T11:30:00Z" },
  { id: "a6", action: "scraper_completed", entityType: "source", details: { scraper: "Google Trends", signals: 18, ideas: 2 }, createdAt: "2026-04-13T10:00:00Z" },
  { id: "a7", action: "pattern_detected", entityType: "pattern", details: { pattern: "Prefers SaaS tools over ebooks", confidence: 0.88 }, createdAt: "2026-04-13T08:00:00Z" },
  { id: "a8", action: "scraper_completed", entityType: "source", details: { scraper: "YouTube", signals: 12, ideas: 1 }, createdAt: "2026-04-12T22:00:00Z" },
];

export const mockScraperStatus = [
  { name: "Reddit", platform: "reddit", status: "idle", lastRun: "2026-04-14T04:00:00Z", nextRun: "2026-04-14T06:00:00Z", signalsTotal: 1247, frequency: "2h" },
  { name: "Google Trends", platform: "google_trends", status: "running", lastRun: "2026-04-14T02:00:00Z", nextRun: "2026-04-14T06:00:00Z", signalsTotal: 456, frequency: "4h" },
  { name: "YouTube", platform: "youtube", status: "idle", lastRun: "2026-04-13T22:00:00Z", nextRun: "2026-04-14T04:00:00Z", signalsTotal: 234, frequency: "6h" },
  { name: "RSS/News", platform: "rss", status: "idle", lastRun: "2026-04-14T03:00:00Z", nextRun: "2026-04-14T04:00:00Z", signalsTotal: 189, frequency: "1h" },
  { name: "Etsy", platform: "etsy", status: "idle", lastRun: "2026-04-13T20:00:00Z", nextRun: "2026-04-14T20:00:00Z", signalsTotal: 87, frequency: "24h" },
  { name: "Whop", platform: "whop", status: "error", lastRun: "2026-04-13T18:00:00Z", nextRun: "2026-04-14T18:00:00Z", signalsTotal: 34, frequency: "24h" },
  { name: "BHW Forums", platform: "bhw", status: "idle", lastRun: "2026-04-13T16:00:00Z", nextRun: "2026-04-13T22:00:00Z", signalsTotal: 56, frequency: "6h" },
];
